### PR TITLE
Add a rules-based solver

### PR DESCRIPTION
**Pull request by dgboy2000**
I loved your kenken program! I wrote a limited rules-based solver for fun and thought it'd make a nice addition to the repo.

### CODE REVIEW

**Comment by dr-skot** [comment]
Hey, you added a solver, that's great! Sorry, I haven't had time to look at it yet, but I'll get to it in the next few days. Thanks!

**Comment by dgboy2000** [comment]
No worries, and feel free with any questions/comments.

**Comment by dr-skot** [comment]
Finally getting around to this. Sorry to keep you waiting. Looks cool, I like it! Also it highlights a weakness of the generator, namely that it doesn't guarantee a unique solution. Which is great, because the solver, once it's perfect (ie never fails to fill an unambiguous cell), can be used to identify ambiguous puzzles and discard them.

I did find a couple of cases where the solver got stumped too early.

unsolved-1

The third cell in the top row has to be 3. It can't be 2 because there's no way to make 8 in the rest of the cage. After that the puzzle solves.

Another one:

unsolved-2

In the bottom right corner, the 1- cage must be 2-3, otherwise the 10+ cage above is impossible. Also, in the bottom left corner (this is trickier): the 100x needs two 5s, so 5-1 is not possible in the 6+ cage above. That 1 has to go in the bottom corner, to dodge the 1 in the 9x cage. A 5 goes above it. Which forces 4-5 in the rest of the 100x box, and so on. This puzzle does prove ambiguous eventually, but 11 of the empty cells are solvable.

So it's a great start! but it does look like there are some more rules to be found. If you come up with any, let me know. I'm working on fully grokking the ones you have. Thanks again!

**Comment by dr-skot** [comment]
I think there's an issue with `getUniques`

```
function getUniques(array) {
    var uniques = {};
    for (var i=0; i<array.length; ++i) {
        uniques[i] = i;
    }
    return getValues(uniques);
}    
```

Should be `uniques[array[i]] = array[i]`, no? Otherwise this just returns the array's index numbers, without looking at its contents.

**Pull request merged**
